# Generated by Django 5.2.1 on 2025-05-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('connection_id', models.CharField(max_length=100)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('query_count', models.PositiveIntegerField(default=0)),
                ('query_time_ms', models.PositiveIntegerField(default=0)),
                ('tables_accessed', models.TextField(blank=True, null=True)),
                ('journal_mode', models.CharField(blank=True, max_length=50, null=True)),
                ('page_size', models.PositiveIntegerField(blank=True, null=True)),
                ('cache_size', models.IntegerField(blank=True, null=True)),
                ('sqlite_version', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Database Connection Log',
                'verbose_name_plural': 'Database Connection Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('engine', models.CharField(default='SQLite', max_length=50)),
                ('version', models.CharField(max_length=20)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('table_count', models.PositiveIntegerField(default=0)),
                ('index_count', models.PositiveIntegerField(default=0)),
                ('journal_mode', models.CharField(default='delete', max_length=20)),
                ('synchronous_setting', models.IntegerField(default=2)),
                ('cache_size', models.IntegerField(default=2000)),
                ('page_size', models.IntegerField(default=4096)),
                ('last_vacuum', models.DateTimeField(blank=True, null=True)),
                ('integrity_check', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Database Status',
                'verbose_name_plural': 'Database Status',
            },
        ),
    ]
